Refactoring import
biobanking/ontology pull request #15
Opened 2021-10-01 22:29 UTC by zhengj2007

Modify import of OBIB, issue: https://github.com/biobanking/biobanking/issues/85

2021-10-04 22:19 UTC, zhengj2007 commented
Details of refactoring documented in the issue, biobanking/biobanking#85

2021-10-05 13:50 UTC, cstoeckert requested changes
OBI_0002125 and OBI_0002126 now have an obsolete parent 'fixed tissue slide specimen' from OMIABIS need to be moved to OBIB_0000661
Do we need geographic location from GAZ as a material entity since we also have geographical entity from GEO?

2021-10-05 15:43 UTC, zhengj2007 commented
Good catch. I updated the ID. The wrong ID brought in due to OBI contains some OMIABIS terms. 

Don't know whether we need 'geographic location'. Keep it for making the refactoring version same as the old one.

2021-10-14 19:11 UTC, cstoeckert approved these changes

2021-10-19 19:45 UTC, merged