Replaced GAZ_00000448 with GEO_000000372
biobanking/ontology pull request #16
Opened 2022-09-13 17:35 UTC by jmwhorton

Replaced GAZ_00000448 'geographic location' with GEO_000000372 'geographical region.'
(issue https://github.com/biobanking/biobanking/issues/86 )

Full Changes:
Replaced GAZ_00000448 with GEO_000000372 in axioms for the following terms:
OBIB_0000641 'settlement part of address'
OBIB_0000656 'biobank location ISO 3166-1 alpha-2 code'

2022-09-13 17:49 UTC, jmwhorton commented
Tagging for visibility
@mbrochhausen @cstoeckert @wdduncan

2022-09-20 17:46 UTC, cstoeckert requested changes
I think the GAZ term geographic location also needs to be removed from imports/externalByhand.owl if it is not being used anymore.

2022-09-21 13:59 UTC, jmwhorton commented
GAZ term geographic location has been removed from the imports.

2022-09-22 14:08 UTC, cstoeckert approved these changes

2023-01-26 20:12 UTC, merged